# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  node-12-executor:
    docker:
      - image: circleci/node:12
    working_directory: ~/example

jobs:
  deploy-ui:
    executor: node-12-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "30:34:0c:22:0b:7d:5e:8b:15:dd:32:d4:dc:26:fd:a7"
      - run:
          name: ECHO BRANCH
          command: echo $(git branch)
      - run:
          name: INSTALL - dependencies
          command: npm install
      - run:
          name: BUILD - App
          command: npm run build
      - run:
          name: DEPLOY - App
          command: npm run deploy

workflows:
  deploy-blog:
    jobs:
      - deploy-ui:
          filters:
            branches:
              only: master

